### PR TITLE
added option :doc to field macro

### PR DESCRIPTION
**Pull request by javobalazs**

### CODE REVIEW

**Comment by javobalazs** [comment]
Sorry, I was not careful with the commit message, I did what I had usually done, and now I can see the problem.

**Comment by javobalazs** [comment]
Okay, I eliminated two credo-complaints related to formatting.

**Comment by ejpcmac** [comment]
No problem, the CI is there for that :)

**Comment by ejpcmac** [comment]
Oh, it seems you still have a failing commit. Could you please rename it according to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? You can force push to your branch, it will update the PR and that should be OK.

**Comment by javobalazs** [comment]
> Oh, it seems you still have a failing commit. Could you please rename it according to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? You can force push to your branch, it will update the PR and that should be OK.

I honestly don't know how to do that. I now made a try but it doesn't look okay.

**Comment by javobalazs** [comment]
Okay, I close it, create another pr, recreate the whole thing.

**Comment by ejpcmac** [comment]
> > Oh, it seems you still have a failing commit. Could you please rename it according to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? You can force push to your branch, it will update the PR and that should be OK.
> 
> I honestly don't know how to do that. I now made a try but it doesn't look okay.

No problem, we are here to learn collectively :slightly_smiling_face: 

For your reference in future works, it is possible to rewrite part of the history using an interactive rebase. There is an article about this in [the GitHub help](https://docs.github.com/en/get-started/using-git/about-git-rebase), and I’ve come to read two other really interesting articles about this recently:

* [Organise your commits](https://www.ncameron.org/blog/organise-your-commits/)
* [Fixing commits with git commit --fixup and git rebase --autosquash](https://jordanelver.co.uk/blog/2020/06/04/fixing-commits-with-git-commit-fixup-and-git-rebase-autosquash/)

I was already applying most of the advice from the first one, but the second one was a complete discovery, and a very neat feature of Git.

When you rewrite the history in such way, you cannot anymore do a simple `git push`, because it has diverged from the remote branch. The solution is to do a `git push --force` to force overwriting the remote branch. However, this needs to be done with caution, because you could erase commits from the remote branch, typically if you are working on the same branch with other people. But when working alone on a branch, such as when building a PR, it’s OK to do so.

I’m also currently writing an article summing up all this + other info, to be published on my blog next week, as I’ve found this could be useful to my colleagues + others on the web.

Thank you for your work anyway, I’ve started to review other PRs tonight, and will review yours tomorrow.

**Pull request closed without merging**
