### PR TITLE
Add visibility option

### PR DESCRIPTION
**Pull request by saleyn**
Implement the visibility option discussed in #27

### CODE REVIEW

**Comment by ejpcmac** [comment]
Hello @saleyn, thank you for your PR! I will review it in the days to come.

**Comment by ejpcmac** [comment]
Hello, I didn’t have the time to review your PRs yet due to a quick increase in my workload on many professional / personal subjects at the same time, which should still be quite high for the coming week and should be decreasing the week after.

I just see that you are targeting the `main` branch. As stated in the [CONTRIBUTING.md](https://github.com/ejpcmac/typed_struct/blob/main/CONTRIBUTING.md#workflow), could you please rebase your changes on top of `develop` and re-target your PRs to `develop` as well? The CI does not run on `main` due to this. Also, commits should be named according to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and use the types defined in [the configuration](https://github.com/ejpcmac/typed_struct/blob/develop/commitlint.config.js#L23-L35). You can take your inspiration from existing commits in the repo.

After that I’ll review and merge this PR first, then your other PR later.

**Comment by saleyn** [comment]
Ok.  I think I'll just do that with the 2nd PR, because it's inclusive of the 1st one.

**Comment by saleyn** [comment]
Closing this PR because it's included in the PR #30

**Pull request closed without merging**
